### ISSUE TITLE
Implementation of convolutional projection

### ISSUE THREAD

**Issue by leoxiaobin** [rishikksh20/convolution-vision-transformers#1]
hi, @rishikksh20 

Thank you for your quick implementation! 

I notice that your depth-wise separable convolution is implemented as depth-wise conv --> point-wise conv. In the paper, CvT's depth-wise seprable convolution is implemented as depth-wise conv --> bn --> point-wise conv. 
![image](https://user-images.githubusercontent.com/5362509/113091468-d4727d80-91a0-11eb-95ca-35149d7b2877.png)

**Comment by rishikksh20** [comment]
@leoxiaobin oh my bad I just reuse my older SepCon2d class in this repo, I will update that class.

**Comment by rishikksh20** [comment]
Done,  do let me  know if you find any other vulnerabilities in code.

**Comment by huixiancheng** [comment]
@leoxiaobin Hi！ When will the official implementation be open source?

**Comment by youngwanLEE** [comment]
@leoxiaobin 
The official code URL denoted in the paper is broken. Do you have a plan to open the code and model weights?

**Comment by leoxiaobin** [comment]
hi, @youngwanLEE, you can get the pre-trained model at https://github.com/microsoft/CvT

**Comment by leoxiaobin** [comment]
> @leoxiaobin Hi！ When will the official implementation be open source?

Please find it at https://github.com/microsoft/CvT

**Comment by rishikksh20** [comment]
Thanks @leoxiaobin I am adding repo on ReadMe.
