### ISSUE TITLE
Implementation of attention module

### ISSUE THREAD

**Issue by MARD1NO** [rishikksh20/convolution-vision-transformers#4]
Hi nice implementation for CvT

Here I have a question is in paper, they use squeezed convolution for computing attention

![image](https://user-images.githubusercontent.com/42901638/114984777-a7260f00-9ec4-11eb-9f3c-8b1b8f2b7977.png)

here the stride of q k v is different。

But in your code, it seems like each attention module use stride as 1

**Comment by rishikksh20** [comment]
@MARD1NO Yes thats flexibily to change your strides, you can change your stride as you desire through function variable
